workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - firebase_credentials

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run analysis
        script: |
          flutter analyze

      - name: Run tests
        script: |
          flutter test

      - name: Build APK
        script: |
          flutter build apk --release

      # IMPORTANT: Build an IPA (not just Runner.app)
      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      firebase:
        # Use Firebase CI token for authentication
        firebase_token: $FIREBASE_TOKEN

        android:
          # Android App ID from Firebase console (Project settings > General)
          app_id: 1:919519153121:android:9f01ada1a3bae37888a0a0
          groups:
            - androidTesters
          artifact_type: apk

        ios:
          # iOS App ID from Firebase console (Project settings > General)
          app_id: 1:919519153121:ios:fd93817fff43360f88a0a0
          groups:
            - iosTesters

      slack:
        channel: "#builds"
        notify_on_build_start: true
