// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuBkM-uQO79TapM3s3WkLttxDMrtREiDU',
    appId: '1:919519153121:web:0eb947a5fadd2e1288a0a0',
    messagingSenderId: '919519153121',
    projectId: 'expensar-a0926',
    authDomain: 'expensar-a0926.firebaseapp.com',
    storageBucket: 'expensar-a0926.firebasestorage.app',
    measurementId: 'G-87FTV2EPBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMAOXcbv2pHVTDw-15hky8eKnlybAAJDY',
    appId: '1:919519153121:android:9f01ada1a3bae37888a0a0',
    messagingSenderId: '919519153121',
    projectId: 'expensar-a0926',
    storageBucket: 'expensar-a0926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHqowh50dHaXvTpp0MYqXu63DvYTC_g38',
    appId: '1:919519153121:ios:fd93817fff43360f88a0a0',
    messagingSenderId: '919519153121',
    projectId: 'expensar-a0926',
    storageBucket: 'expensar-a0926.firebasestorage.app',
    iosBundleId: 'com.example.expensar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHqowh50dHaXvTpp0MYqXu63DvYTC_g38',
    appId: '1:919519153121:ios:fd93817fff43360f88a0a0',
    messagingSenderId: '919519153121',
    projectId: 'expensar-a0926',
    storageBucket: 'expensar-a0926.firebasestorage.app',
    iosBundleId: 'com.example.expensar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuBkM-uQO79TapM3s3WkLttxDMrtREiDU',
    appId: '1:919519153121:web:0108aeb13c4ee11c88a0a0',
    messagingSenderId: '919519153121',
    projectId: 'expensar-a0926',
    authDomain: 'expensar-a0926.firebaseapp.com',
    storageBucket: 'expensar-a0926.firebasestorage.app',
    measurementId: 'G-L8YHK6XLHS',
  );
}
