# Set the platform to 15.0 to satisfy Firebase requirements
platform :ios, '15.0'

# This helper script is required to bridge Flutter and CocoaPods
path_to_utils = File.expand_path(File.join('..', '..', 'flutter', 'packages', 'flutter_tools', 'bin', 'xcode_backend.sh'), __FILE__)

# Standard Flutter setup
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This is the line that was failing because it needed the Flutter script context
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Force every plugin to use iOS 15.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end